export const ACTION_EMAIL_VERIFY = 'ACTION_EMAIL_VERIFY'
export const ACTION_REGISTER_USER = 'ACTION_REGISTER_USER'
export const ACTION_GET_USER_DATA = 'ACTION_GET_USER_DATA'
export const ACTION_UPDATE_SOCIAL_LINKS = 'ACTION_UPDATE_SOCIAL_LINKS'


