export const ACTION_EMAIL_VERIFY = 'ACTION_EMAIL_VERIFY'
export const ACTION_REGISTER_USER = 'ACTION_REGISTER_USER'
export const ACTION_GET_USER_DATA = 'ACTION_GET_USER_DATA'
export const ACTION_UPDATE_SOCIAL_LINKS = 'ACTION_UPDATE_SOCIAL_LINKS'
export const ACTION_GET_USER_FAVORITE_POSTS_WITH_PAGINATION = 'ACTION_GET_USER_FAVORITE_POSTS_WITH_PAGINATION'
export const ACTION_GET_USER_COMMENT_POSTS_WITH_PAGINATION = 'ACTION_GET_USER_COMMENT_POSTS_WITH_PAGINATION'




