export const MUTATION_SEED_TEXT_EDITOR_DATA = 'MUTATION_SEED_TEXT_EDITOR_DATA'
export const MUTATION_EVENT_SHOW_PREVIEW = 'MUTATION_EVENT_SHOW_PREVIEW'
export const MUTATION_NOTIFY = 'MUTATION_NOTIFY'
export const MUTATION_SIGN_UP_DATA = 'MUTATION_SIGN_UP_DATA'

export const MUTATION_SEED_USER_DATA = 'MUTATION_SEED_USER_DATA'