export const ACTION_GET_PROFILE_DATA = 'ACTION_GET_PROFILE_DATA'
export const ACTION_GET_PROFILE_FAVORITED_POSTS =
  'ACTION_GET_PROFILE_FAVORITED_POSTS'
export const ACTION_GET_PROFILE_COMMENTED_POSTS =
  'ACTION_GET_PROFILE_COMMENTED_POSTS'
export const ACTION_UPDATE_PROFILE_SOCIAL_LINKS =
  'ACTION_UPDATE_PROFILE_SOCIAL_LINKS'
