export const MUTATION_PROFILE_DATA = 'MUTATION_PROFILE_DATA'
export const MUTATION_PROFILE_FAVORITED_POSTS =
  'MUTATION_PROFILE_FAVORITED_POSTS'
export const MUTATION_PROFILE_COMMENTED_POSTS =
  'MUTATION_PROFILE_COMMENTED_POSTS'
