export { calculateDelay } from './calculateDelay'
export { chooseAvatars, descriptions, socialNetworks, techs } from './data'
export type { IAvatars, SocialNetwork, Techs } from './data'
export { dateFormat } from './dateFormat'
export { detectClickOutsideElement } from './detectClickOutsideElement'
export { getAvatarUrlById } from './getAvatarUrlById'
export { handleMarkdown } from './handleMarkdown'
export { isEven } from './isEven'
export { setCookie } from './setCookie'
