### POST
POST http://localhost:3000/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZTBjNTYzNWMtZDVkZC00NDExLWE4YmQtYjYyNjA3NWVjNGI0IiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ0eXBlIjoiYXV0aG9yIiwidXNlcm5hbWUiOiJsaW5rIiwiYXZhdGFySWQiOiJGYXZhdGFyMDIiLCJpYXQiOjE2ODcwMTIyNDUsImV4cCI6MTY4NzYxNzA0NX0.2yj1A7duQ2y3_VPJVOvtZ57aSzwTLM749KtItjtTDT0

{
 "title": "Post 8",
 "body": "Taaaaaaa",
 "tags": ["typescript", "typescript", "typescript", "web"],
 "coverImage": "https://res.cloudinary.com/dm7h7e8xj/image/upload/v1504810464/hello-world-vue_ibatoy.jpg",
 "postedAt": "2023-05-30T14:31:44.545Z",
 "author": {
    "id": "8c96ecb9-cb30-45ef-a134-3b10f0e3221c",
    "email": "email@email.com",
    "username": "link",
    "avatar": "Favatar02",
    "userRole": "author"
  }
}
###
GET http://localhost:3000/post
###
GET http://localhost:3000/post/b6028ed9-233d-49a5-85c3-bdd7c8886bf6
###
GET http://localhost:3000/post/slug/meu-post
###
GET http://localhost:3000/post/pagination?skip=6&pageSize=6
###
GET http://localhost:3000/post/pagination/userFavorites?userId=57efe66a-ec3a-4043-9db9-bc40ce5a6a01&skip=0&pageSize=3
###
GET http://localhost:3000/post/title?equals=nestjs
###
GET http://localhost:3000/post/pagination/filteringTags?tag=aaaa&skip=0&pageSize=8
###
PUT http://localhost:3000/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNlZWVjZjctOTMwNi00Mjg0LTljZTEtYzdiNDYwZDg5NDM2IiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ0eXBlIjoiYXV0aG9yIiwidXNlcm5hbWUiOiJsaW5rIiwiYXZhdGFySWQiOiJGYXZhdGFyMDIiLCJpYXQiOjE2ODY2MDk4MTEsImV4cCI6MTY4NzIxNDYxMX0.-6kHYogc1BKyERi0R5H5u97hZtjYiR8Xgt0U2xc4ogY

{
 "id": "5ac72c89-7aaa-4e70-8f16-50598d687119",
 "title": "NestJS",
 "body": "Post atualizado",
 "tags": ["typescript", "nestjs", "nodejs", "web"],
 "coverImage": "https://res.cloudinary.com/dm7h7e8xj/image/upload/v1504810464/hello-world-vue_ibatoy.jpg",
 "postedAt": "2023-05-30T14:31:44.545Z",
 "author": {
    "id": "e0c5635c-d5dd-4411-a8bd-b626075ec4b4",
    "email": "email@email.com",
    "username": "link",
    "avatar": "AVATAR01"
  }
}
###
DELETE http://localhost:3000/post/b79a3953-6621-48f9-9f30-6a1059583da1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNlZWVjZjctOTMwNi00Mjg0LTljZTEtYzdiNDYwZDg5NDM2IiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ0eXBlIjoiYXV0aG9yIiwidXNlcm5hbWUiOiJsaW5rIiwiYXZhdGFySWQiOiJGYXZhdGFyMDIiLCJpYXQiOjE2ODY2MDk4MTEsImV4cCI6MTY4NzIxNDYxMX0.-6kHYogc1BKyERi0R5H5u97hZtjYiR8Xgt0U2xc4ogY


### USER
POST http://localhost:3000/user/verifyEmail/stardusteight.d4cc@gmail.com
###
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "email": "emaissl@email.com",
  "username": "lisnks",
  "password": "password07",
  "avatar": "Favatar02",
  "userRole": "author"
}
###
GET http://localhost:3000/user/username/stardust
###
GET http://localhost:3000/user/username?equals=xablau
###
GET http://localhost:3000/user/63eeecf7-9306-4284-9ce1-c7b460d89436
###
GET http://localhost:3000/user/signin?identifier=stardusteight.d4cc@gmail.com&password=pa$$word1
###
PUT http://localhost:3000/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNlZWVjZjctOTMwNi00Mjg0LTljZTEtYzdiNDYwZDg5NDM2IiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ0eXBlIjoiYXV0aG9yIiwidXNlcm5hbWUiOiJsaW5rIiwiYXZhdGFySWQiOiJGYXZhdGFyMDIiLCJpYXQiOjE2ODY2MDk4MTEsImV4cCI6MTY4NzIxNDYxMX0.-6kHYogc1BKyERi0R5H5u97hZtjYiR8Xgt0U2xc4ogY

{
  "email": "email@email.com",
  "username": "link",
  "avatar": "Favatar02",
  "userRole": "author",
  "socialLinks": {
    "github": "https://github.com/stardusteight-d4c"
  }
}


### FAVORITE
GET http://localhost:3000/favorite/amount?of=post&id=5d933a3f-2630-4079-a70b-f18f8f2db2ac
###
PUT http://localhost:3000/favorite/toggle
Content-Type: application/json

{ 
  "postId": "5d933a3f-2630-4079-a70b-f18f8f2db2ac",
  "userId": "83843402-b4ff-462b-9727-89126fa5b32e" 
}


### COMMENT
POST http://localhost:3000/comment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNlZWVjZjctOTMwNi00Mjg0LTljZTEtYzdiNDYwZDg5NDM2IiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ0eXBlIjoiYXV0aG9yIiwidXNlcm5hbWUiOiJsaW5rIiwiYXZhdGFySWQiOiJGYXZhdGFyMDIiLCJpYXQiOjE2ODY2MDk4MTEsImV4cCI6MTY4NzIxNDYxMX0.-6kHYogc1BKyERi0R5H5u97hZtjYiR8Xgt0U2xc4ogY

{
  "postId": "e8dfe910-a5b0-4b71-98e6-555506cfef1d",
  "postTitle": "Sample Post",
  "owner": {
    "id": "51900c55-0dfd-4bbf-a8b4-84f54d9fab07",
    "email": "johndoe@email.com",
    "username": "johndoe",
    "avatar": "AVATAR01",
  },
  "content": "Great post! I really enjoyed reading it.",
  "postedAt": "2023-05-30T14:31:44.545Z"
}
###
GET http://localhost:3000/comment/amount?of=user&id=b85d3a17-355f-4735-833c-c5468fecc98c
###
GET http://localhost:3000/comment/pagination?by=postId&value=c5d68477-129e-4cc0-8f36-e8ddc9874519&skip=2&pageSize=2
###
GET http://localhost:3000/comment/pagination?by=userId&value=b85d3a17-355f-4735-833c-c5468fecc98c&skip=0&pageSize=3
###
PUT http://localhost:3000/comment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNlZWVjZjctOTMwNi00Mjg0LTljZTEtYzdiNDYwZDg5NDM2IiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ0eXBlIjoiYXV0aG9yIiwidXNlcm5hbWUiOiJsaW5rIiwiYXZhdGFySWQiOiJGYXZhdGFyMDIiLCJpYXQiOjE2ODY2MDk4MTEsImV4cCI6MTY4NzIxNDYxMX0.-6kHYogc1BKyERi0R5H5u97hZtjYiR8Xgt0U2xc4ogY


{
  "id": "b85d3a17-385f-4747-833c-c5468fecc98c",
  "postId": "e8dfe910-a5b0-4b71-98e6-555506cfef1d",
  "postTitle": "Sample Post",
  "owner": {
    "id": "51900c55-0dfd-4bbf-a8b4-84f54d9fab07",
    "email": "johndoe@email.com",
    "username": "johndoe",
    "avatar": "AVATAR01",
  },
  "content": "Updated comment!",
  "postedAt": "2023-05-30T14:31:44.545Z"
}
###
DELETE http://localhost:3000/comment/b85d3a17-385f-4747-833c-c5468fecc98c?ownerId=51900c55-0dfd-4bbf-a8b4-84f54d9fab07
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNlZWVjZjctOTMwNi00Mjg0LTljZTEtYzdiNDYwZDg5NDM2IiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ0eXBlIjoiYXV0aG9yIiwidXNlcm5hbWUiOiJsaW5rIiwiYXZhdGFySWQiOiJGYXZhdGFyMDIiLCJpYXQiOjE2ODY2MDk4MTEsImV4cCI6MTY4NzIxNDYxMX0.-6kHYogc1BKyERi0R5H5u97hZtjYiR8Xgt0U2xc4ogY

