export { default as Header } from './Header.vue'
export { default as SocialLinks } from './SocialLinks.vue'
export { default as PostComment } from './PostComment.vue'
export { default as StarredPosts } from './StarredPosts.vue'
export { default as CommentedPosts } from './CommentedPosts.vue'
